name: Randomized Package Test

on:
  workflow_dispatch:

  schedule:
    - cron: "0 * * * *" # every hour

jobs:
  randomized-test:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Decide Random Execution
        id: random_check
        run: |
          NUMBER=$((RANDOM % 100))

          echo "Random number: $NUMBER"

          # 50% chance to continue
          if [ "$NUMBER" -lt 50 ]; then
            echo "run_job=true" >> $GITHUB_OUTPUT
          else
            echo "run_job=false" >> $GITHUB_OUTPUT
          fi

      - name: Skip Run
        if: steps.random_check.outputs.run_job == 'false'
        run: echo "Skipping this cycle"

      - name: Random Delay
        if: steps.random_check.outputs.run_job == 'true'
        run: |
          DELAY=$((RANDOM % 300))
          echo "Sleeping for $DELAY seconds"
          sleep $DELAY

      - name: Create Temp Project
        if: steps.random_check.outputs.run_job == 'true'
        run: |
          mkdir test-app
          cd test-app
          npm init -y

      - name: Randomized Install Count
        if: steps.random_check.outputs.run_job == 'true'
        run: |
          cd test-app

          COUNT=$(( (RANDOM % 3) + 1 ))

          echo "Running $COUNT install tests"

          for i in $(seq 1 $COUNT)
          do
            echo "Test run $i"

            rm -rf node_modules package-lock.json

            npm install create-server-startup
          done
